services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8080:80"
    environment:
      MYSQL_PASS: dvwa
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: dvwa
      MYSQL_DATABASE: dvwa
    volumes:
      - mysql-data:/var/lib/mysql

  ftp:
    image: fauria/vsftpd
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      FTP_USER: "ftpuser"
      FTP_PASS: "ftppass"
      PASV_ADDRESS: "127.0.0.1"
      PASV_MIN_PORT: "21000"
      PASV_MAX_PORT: "21010"
      LOG_STDOUT: "Yes"

  ssh:
    image: linuxserver/openssh-server
    ports:
      - "2222:2222"
    environment:
      PUID: 1000
      PGID: 1000
      PASSWORD_ACCESS: true
      USER_NAME: sshuser
      USER_PASSWORD: sshpass
      SUDO_ACCESS: false

volumes:
  mysql-data:
